project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!rv/"

website:
  title: "hcmc_geo_change"
  navbar:
    left:
        - index.qmd


format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual

